[tool.poetry]
name = "torch_accel"
version = "0.1.0"
license = "MIT"
readme = "README.md"
description = ""
authors = ["yohan-pg <pg.yohan@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
torch = "^1.11.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
