[tool.poetry]
name = "zd.testt"
version = "0.1.0"
description = ""
authors = ["michael-drozdov-zocdoc <86305671+michael-drozdov-zocdoc@users.noreply.github.com>"]
packages = [
    { include = "zd", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.7"
python-dateutil = ">=2.4.2"
pytz = "2013.7"
datadog = "^0.44.0"
mock = "^4.0.3"
boto3 = "^1.23.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
