[tool.poetry]
name = "bpsci_dev"
version = "0.0.18"
description = ""
authors = ["Jerry Varghese <varghese.jerryj@gmail.com>"]
include = ["assets/*"]

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1.18.4"
scipy = "^1.7.3"
pandas = "^1.2.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
