[project]
name = "pkm"
version = "0.4.44"
description = "Package Manager For Python"
authors = [{ name = "bennyl" }]
license.text = "MIT License"
readme.file = "README.md"
requires-python = ">=3.8, <4.0"

[build-system]
build-backend = "pkm.api.buildsys"
backend-path = ["src"]
requires = []