[tool.poetry]
name = "solace"
version = "0.1.21"
description = "A Modern Framework for Building Python Web Apps"
authors = ["Dan Sikes <dansikes7@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
starlette = "^0.19.0"
typer = {extras = ["all"], version = "^0.4.1"}
loguru = "^0.6.0"
Jinja2 = "^3.1.1"
uvicorn = "^0.17.6"
watchgod = "^0.8.2"
Cerberus = "^1.3.4"
python-multipart = "^0.0.5"
boltons = "^21.0.0"
python-magic = "^0.4.25"
libmagic = "^1.0"
pyaml = "^21.10.1"
python-box = "^6.0.2"
databases = {extras = ["aiomysql"], version = "^0.5.5"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
solace = 'solace.cli:cli'
