[tool.poetry]
name = "async-tg-bot"
version = "0.1.5"
description = ""
authors = ["levch <levchenko.d.a1998@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
python-dotenv = "^0.20.0"
pydantic = "^1.9.0"
requests = "^2.27.1"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
