[tool.poetry]
name = "litcommit"
version = "0.1.16"
description = "No more commenting your code: Use the GPT3-based CodeCommenter"
authors = ["Standard Data, Inc. <contact@standarddata.ai>"]

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.1.3"
requests = "^2.27.1"
GitPython = "^3.1.27"
typer = "^0.4.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
#  The front is the command   start  , =  And then   Appoint typer example ,  The corresponding is   Package name . Module name (main.py file ).typer Object name 
lit = 'litcommit.main:main'
