name: follicle-finder
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=1.10.1
  - cudatoolkit=11.3
  - pip>=22.0
  - pip:
    - pytorch3dunet @ https://github.com/kevinyamauchi/pytorch-3dunet/tarball/memory_dataset#egg=pytorch3dunet-1.3.3
    - ovary-analysis
