[tool.poetry]
name = "rispack"
version = "0.2.0"
description = "Pack of shared libraries from Rispar"
authors = ["Rispar Tecnologia <tecnologia@rispar.com.br>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
SQLAlchemy = "^1.4.36"
boto3 = "^1.23.3"
aws-lambda-powertools = "^1.25.10"
requests-aws-sign = "^0.1.6"
marshmallow = "^3.15.0"
marshmallow-dataclass = "^8.5.8"

[tool.poetry.dev-dependencies]
twine = "^4.0.0"
black = "^22.3.0"
isort = "^5.10.1"
pytest = "^7.1.2"
moto = "^3.1.9"
pytest-cov = "^3.0.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
