[tool.poetry]
name = "aurflux"
version = "4.0.4"
description = "Aurflux!"
authors = ["Zenith <inbox@zenith.dev>"]
include = ["aurflux/py.typed"]

[tool.poetry.dependencies]
python = ">=3.10"
py-cord = "*"
aurcore = "^1.1"
pyyaml = "*"
loguru = "^0.5.2"
tabulate = "^0.8.7"
dateparser = "^1.0.0"

[tool.poetry.dev-dependencies]
"discord.py-stubs" = "^fe1.4.0"
mypy = "^0.782"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
