[tool.poetry]
name = "utils-tddschn"
version = "0.1.6"
description = ""
authors = ["Xinyuan Chen <45612704+tddschn@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/tddschn/utils-tddschn"
repository = "https://github.com/tddschn/utils-tddschn"
keywords = ["numpy", "utility"]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/tddschn/utils-tddschn/issues"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
toml = "^0.10.2"
yapf = "^0.32.0"
better-exceptions = "^0.3.3"
bump2version = "^1.0.1"
black = "^22.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
