[tool.poetry]
name = "two-tables"
version = "0.1.2"
description = "Automatically update two tables"
authors = ["LilyWhite <lilywhite2005@outlook.com>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.7"
openpyxl = "^3.0.10"
docopt = "^0.6.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
two_tables = 'two_tables.updater:main'
