# https://python-poetry.org/

[tool.poetry]
name = "pydamain"
version = "0.4.5"
description = "도메인 주도 설계 라이브러리."
license = "Apache-2.0"
authors = ["Jongbeom-Kwon <bolk9652@naver.com>"]
readme = "README.md"
repository = "https://github.com/by-Exist/pydamain"
packages = [
    { include = "pydamain", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.10"
typing-extensions = "^4.2.0"
SQLAlchemy = {version = "^1.4.36", optional = true}
aiosmtplib = {version = "^1.1.6", optional = true}

[tool.poetry.extras]
sqlalchemy = ["SQLAlchemy"]
aiosmtplib = ["aiosmtplib"]

[tool.poetry.dev-dependencies]
black = "^22.3.0"
pytest = "^7.1.2"
pytest-asyncio = "^0.18.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
