[tool.poetry]
name = "amora"
version = "0.1.10rc6"
description = "Amora Data Build Tool"
authors = ["diogommartins <diogo.martins@stone.com.br>"]
license = "MIT"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: SQL",
]

[tool.poetry.dependencies]
python = ">=3.9.6,<3.10"
pandas = "^1.3.0"
numpy = "^1.21.1"
matplotlib = "^3.4.2"
sqlmodel = "^0.0.4"
sqlalchemy-bigquery = "^1.2"
networkx = { extras = ["all"], version = "^2.6.3" }
typer = { extras = ["all"], version = "^0.4.0" }
pytest = "^6.2.5"
pytest-xdist = { extras = ['psutil'], version = "^2.5.0" }
rich = "^10.13.0"
Jinja2 = "^3.0.3"
sqlparse = ">=0.3.1,<0.5.0"
SQLAlchemy = { version = "1.4.35", extras = ["mypy"] }
feast = { version = "0.18.0", extras = ["redis", "gcp"], optional = true }
Werkzeug = { version = "2.0.0", optional = true }                   # Bug no dash, com issue conhecida
dash = { version = "2.1.0", optional = true }
dash-cytoscape = { version = "0.2.0", optional = true }
protobuf = "<3.20.0"

[tool.poetry.dev-dependencies]
pytest-cov = "^3.0.0"
black = "^22.1"
jupyter = "^1.0.0"
mypy = "^0.941"
lxml = "^4.6.3"
pytest-env = "^0.6.2"
mkdocs-material = "8.2.9"
mkdocs-minify-plugin = "^0.5.0"
mkdocs-redirects = "^1.0.3"
mkdocs-git-revision-date-plugin = "^0.3.1"
mkdocs-include-markdown-plugin = "^3.2.3"
mkdocs-autorefs = "^0.4.1"
mkdocstrings = { version = "^0.18.0", extras = ["python"] }
shed = "^0.9.5"
pre-commit = "^2.18.1"
mkdocs-jupyter = "^0.20.1"
pandas-stubs = "^1.2.0"

[tool.poetry.extras]
feature-store = ["feast"]
dash = ["dash", "dash-cytoscape", "Werkzeug"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."pytest11"]
amora = "amora.tests.pytest_plugin"

[tool.poetry.scripts]
amora = "amora.cli:main"

[tool.mypy]
plugins = ["sqlalchemy.ext.mypy.plugin"]
