[tool.poetry]
name = "cached_secrets_manager"
version = "0.1.13-dev.20220523083815"
description = ""
authors = ["Maximilian Walther <max@spryfox.de>"]

[tool.poetry.dependencies]
python = "^3.8.12"
boto3 = "^1.21.20"
botocore = "^1.24.20"

[tool.poetry.dev-dependencies]
pytest = "^7.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
