[tool.poetry]
name = "wekan-logstash"
version = "0.1.6"
description = "Simple script that will print cards data for logstash (ELK Kibana) in JSON format"
authors = ["Franklin Gomez <fgomezotero@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/fgomezotero/wekan-logstash"
documentation = "https://fgomezotero.github.io/wekan-logstash/"
keywords = [
    "wekan",
    "logstash"
]
packages = [
    { include = "wekan_logstash", from = "src" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: Implementation",
    "License :: OSI Approved :: MIT License"
]
[tool.poetry.urls]
"Bug Tracker" = "https://github.com/fgomezotero/wekan-logstash/issues"

[tool.poetry.scripts]
get_cards = 'wekan_logstash.cli:cli'

[tool.poetry.dependencies]
python = ">=3.8"
pymongo = ">=4.1.1"
python-slugify = ">=6.1.2"
requests = ">=2.27.1"
Unidecode = ">=1.3.4"
click = ">=8.1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
