[tool.poetry]
name = "lightningflow"
version = "0.1.4"
description = "A workflow template designed for optical transceiver test."
authors = ["Chongjun Lei <chongjun.lei@neophotonics.com>"]
license = "GPL-3.0-or-later"
repository = "https://github.com/asakiasako/LIGHTNINGFLOW"

[tool.poetry.dependencies]
python = "^3.8"
networkx = "^2.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
