# path to the checkpoint file containing the model
model_path: 'ovary_3dunet.pytorch'
# model configuration
model:
  # model class
  name: UNet3D
  # number of input channels to the model
  in_channels: 1
  # number of output channels
  out_channels: 2
  # determines the order of operators in a single layer (gcr - GroupNorm+Conv3d+ReLU)
  layer_order: gcr
  # feature maps scale factor
  f_maps: [32, 64, 128, 256]
  # number of groups in the groupnorm
  num_groups: 8
  # apply element-wise nn.Sigmoid after the final 1x1 convolution, otherwise apply nn.Softmax
  final_sigmoid: true
  # if True applies the final normalization layer (sigmoid or softmax), otherwise the networks returns the output from the final convolution layer; use False for regression problems, e.g. de-noising
  is_segmentation: false
# predictor configuration
predictor:
  # standard in memory predictor
  name: 'InMemoryPredictor'
# specify the test datasets
loaders:
  # dataset type
  dataset: 'MemoryDataset'
  # batch dimension; if number of GPUs is N > 1, then a batch_size of N * batch_size will automatically be taken for DataParallel
  batch_size: 1
  # mirror pad the raw data in each axis for sharper prediction near the boundaries of the volume
  mirror_padding: [32, 32, 32]
  # path to the raw data within the H5
  raw_internal_path: raw_rescaled
  # how many subprocesses to use for data loading
  num_workers: 0
  # test loaders configuration
  test:
    # paths to the test datasets; if a given path is a directory all H5 files ('*.h5', '*.hdf', '*.hdf5', '*.hd5')
    # inside this directory will be included as well (non-recursively)
    file_paths:
      - ''
    # SliceBuilder configuration, i.e. how to iterate over the input volume patch-by-patch
    slice_builder:
      # SliceBuilder class
      name: SliceBuilder
      # train patch size given to the network (adapt to fit in your GPU mem, generally the bigger patch the better)
      patch_shape: [80, 80, 80]
      # train stride between patches
      stride_shape: [20, 20, 20]

    transformer:
        raw:
          - name: Standardize
          - name: ToTensor
            expand_dims: true
