[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "football_domain"
authors = [{name = "PaweÅ‚ Samoraj", email = "samoraj.pawel@gmail.com"}]
dynamic = ["version", "description"]

[project.urls]
Home = "http://samoraj.pl"
